### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tomitrescak** [basarat/eze#1]
Looks pretty good! Nice and lightweight. Since each component I see separate I guess configuring jest snapshots should be straightforward, but would be great to see the demo for this;)

Also, how would you approach multiple pages of components with some navigation in between? Does it have some kind of router? I have more then 400 components in my project and would be great to create some kind of navigation.

**Comment by basarat** [comment]
>  I have more then 400 components in my project and would be great to create some kind of navigation.

For now a page a navigation will be built automatically using the markdown parsing of headings

With 400 components you might want *multiple* pages. Haven't thought too much about how to manage that. I have considered a `renderAll` function but not on the roadmap for now.

Also highly appreciate you such early feedback :) :heart: :rose:

**Comment by colelawrence** [comment]
@tomitrescak I could see the future having the extensibility of producing many pages dynamically. So, I could easily dynamically create many pages from my components.

**This is just a thought! ->**
```typescript
// glob files
declare function glob(pattern: string): { dirName, fileNames: string[] }[];
declare function readFile(dir, filename): string;
import { createFolder, Folder, DocumentFile, Document } from 'eze'

const docs: Folder = createFolder('docs')

glob('./src/app/**/*.md').forEach(
    ( {dirName, fileNames} ) => {
  let folder: Folder = docs.mkdirp(dirName)
  fileNames.forEach(
      fileName => {
    let doc: DocumentFile = folder.doc(fileName)
    let section: Document = doc.section(fileName)
    section.code(/* Some code */)
    section.md(/* Some markdown */)
    // another section
    let footer: Document = doc.section()
    footer.md(`Generated: ${(new Date).toISOString()}`)
  })
})

```

**Comment by basarat** [comment]
@ZombieHippie just wanted to share what I still have in my mind: 
* If added `renderAll` will bring in `glob` internally so users don't need to do more setup than needed.
* Also using `fs-extra` so I don't need `mkdirp` : https://github.com/jprichardson/node-fs-extra Has great `@types` support too ;) :rose:

**Comment by basarat** [comment]
@tomitrescak added `story` support ;) http://basarat.com/eze/#stories Hopefully will wrap this up over the weekend for a release :heart:

**Comment by basarat** [comment]
Introduced this at work and it does everything we need it to do for now so closing as will not be adding any more features myself :rose: Hope this project helps you guys as well :heart:
